# Generated by Django 5.2 on 2025-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_supply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(max_length=100)),
                ('kilos_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kilo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
