# Generated by Django 5.2 on 2025-05-15 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Employee Info', 'verbose_name_plural': 'Employee Info'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='description',
        ),
        migrations.AddField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(default='Staff', max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='member',
            name='schedule',
            field=models.CharField(default='9AM-5PM', max_length=100),
        ),
    ]
