# Generated by Django 5.2.1 on 2025-05-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0008_salesreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewOnlyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'verbose_name': 'View Only Group',
                'verbose_name_plural': 'View Only Groups',
            },
        ),
    ]
