# Generated by Django 5.2 on 2025-05-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_viewonlygroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewOnlyGroup',
        ),
    ]
